### ISSUE TITLE
Keyboard remap plist code, Sonoma 14.7 stopped working

### ISSUE THREAD

**Issue by dergolem** [naiyerasif/site#22]
This worked in the last version of Sonoma. I installed the 14.7 update today, the key map doesn't work. Verified that the plist is still in place and identical to the posted code.

**Comment by dergolem** [comment]
Even after several restarts, could not get the key map to work. 
Found this: https://mybyways.com/blog/remapping-physical-function-keys-on-macbook-pros 
which suggested using "launchctl load ~/Library/LaunchAgents/com.local.KeyRemapping.plist" command in Terminal. Key map now works.

**Comment by naiyerasif** [comment]
Interesting. I did test the remapping on 14.7 and 15, and it works on both versions. As long as the utility remains on the list of Login Items, it should world. Maybe something has removed it from the Login Items on your system.

**Comment by naiyerasif** [comment]
That's what that plist file is doing. It adds a Login Item so that every time your Mac starts, the keymap remapping is initialized. Fun fact, you can add many other things that you want to do on Mac startup this way.

**Comment by dergolem** [comment]
Wow, that’s really cool. Thank you so much for explaining how it works. I’ll make sure not to turn it off.
